### ISSUE TITLE
Inverse the boolean => if false, throw an error

### ISSUE THREAD

**Issue by Garinlu** [ReliefApplications/notifications-bundle#1]
https://github.com/ReliefApplications/notifications-bundle/blob/70f4c5d2ab0bf4420d41390d6bbd7032611e4385/Model/Pusher/IosPusher.php#L100

**Comment by blixit** [comment]
[https://github.com/ReliefApplications/notifications-bundle/commit/b4d0046e76ddfe3d962f234ee99591c0010cf4fa](https://github.com/ReliefApplications/notifications-bundle/commit/b4d0046e76ddfe3d962f234ee99591c0010cf4fa)
